[Display]

# Change this to change the background color of the display
background_color = '#282a36'

# Change this to change the line color used to draw the grid on
# display
line_color = '#f8f8f2'

[World]

# Change this to set how big of a world you want to work with
# Changing this to a very big number may make the game unplayable as
# the grid cells will become very small and indistinguishable
size = 5

# Base world progression speed in milliseconds
# In game you can speed this up or slow it down by order or 2 upto
# two times in both direction of number line.
speed = 1000